"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "./ThemeContext";
import SideProgressBar from "@/components/SideProgressBar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Colorado Conference Connection",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { scrollData, setScrollData } = useState<React.SyntheticEvent<
    HTMLDivElement,
    WheelEvent
  > | null>(null);

  const handleScroll = (
    event: React.SyntheticEvent<HTMLDivElement, WheelEvent>
  ) => {
    setScrollData(event);
  };

  return (
    <html lang="en">
      <body className="bg-bg text-content" onScroll={handleScroll}>
        <ThemeProvider>
          <SideProgressBar data={scrollData} />
          <NavBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

//  className={inter.className}
